// 기존 UI가 사용하는 공개 함수 이름을 OD 수요·구간 재고 엔진에 연결한다.
const _bookedCache={},_congCache={},_levelCache={};
function loadCongestion(){return _bookedCache}function saveCongestion(x){Object.assign(_bookedCache,x)}
function _ct(no){return typeof getTrainByNo==='function'?getTrainByNo(no):null}
function _cd(d){return d||(typeof todayLocalStr==='function'?todayLocalStr():new Date().toISOString().slice(0,10))}
function _od(no,a,b){if(a&&b)return[a,b];const q=window._bArgs;if(q&&String(q.trainNo)===String(no)&&q.fromStn&&q.toStn)return[q.fromStn,q.toStn];const s=NIMBI_Demand?.getStops(_ct(no))||[];return[s[0]?.s,s.at(-1)?.s]}
function getBookedSeats(no,date,from,to){date=_cd(date);const t=_ct(no),[a,b]=_od(no,from,to),s=NIMBI_Demand?.getStops(t).map(x=>x.s)||[],fi=s.indexOf(a),ti=s.indexOf(b),out=new Set;for(const x of(typeof loadTickets==='function'?loadTickets():[])){if(String(x.trainNo)!==String(no)||x.travelDate!==date||x.status!=='active')continue;const i=s.indexOf(x.fromStn),j=s.indexOf(x.toStn);if(fi<0||ti<0||i<ti&&fi<j)for(const z of x.seats||[])out.add(z)}for(const z of _bookedCache[`${no}:${date}:${a}:${b}`]||[])out.add(z);return out}
function getLineDemand(no,g,w){const t=_ct(no);return t?Math.max(.35,Math.min(1.4,getBaseDemandIndex(t)*(w?1.05:1))):.5}
function getStnBonus(){return 0}function getHourDemand(h,w){return w?(h<6?.3:h<10?.75:h<17?.9:h<21?.82:.55):(h<6?.28:h<10?.96:h<16?.72:h<21?.94:.5)}
function getDateProximityFactor(d){return getBookingProgress((new Date(d+'T12:00:00')-new Date())/36e5,'regional')}
function getGradeCarFactor(t){return t==='free'?0:t==='special'||t==='premium'?.78:1}
function calcRealisticFillRate(no,date,dep,grade,from,to){const t=_ct(no),c=t&&NIMBI_Inventory?.getCongestion(t,from,to,_cd(date));return Math.max(0,Math.min(1,c?.rate||0))}
function _allSeats(comp){const out=[];for(const c of comp||[]){if(c.type==='free')continue;const m=new Set(c.missingSeats||[]);for(let r=1;r<=(c.rows||20);r++)for(const col of c.cols||[])if(!m.has(`${r}${col}`))out.push(typeof seatId==='function'?seatId(c,r,col):`${c.car}호차 ${r}${col}`)}return out}
function generateVirtualBookings(no,date,comp,from,to){date=_cd(date);const[a,b]=_od(no,from,to),key=`${no}:${date}:${a}:${b}`;if(_bookedCache[key])return;const c=NIMBI_Inventory?.getCongestion(_ct(no),a,b,date),all=_allSeats(comp),n=Math.min(all.length,c?.booked||0),seed=NIMBI_Demand.hash(`${no}|${date}|${a}|${b}|seat`);all.sort((x,y)=>NIMBI_Demand.hash(seed+x)-NIMBI_Demand.hash(seed+y));_bookedCache[key]=all.slice(0,n);_congCache[key]=true}
function getCongestionLevel(no,date,comp,from,to){const[a,b]=_od(no,from,to),c=NIMBI_Inventory?.getCongestion(_ct(no),a,b,_cd(date));if(!c)return{rate:0,label:'',color:'',available:0};return{...c,label:c.level,color:c.percent>90?'var(--red)':c.percent>75?'var(--orange)':c.percent>55?'var(--accent2)':'var(--green)'}}
function getCarRemaining(no,date,car,from,to){generateVirtualBookings(no,date,[car],from,to);const used=getBookedSeats(no,date,from,to),m=new Set(car.missingSeats||[]);let total=0,n=0;for(let r=1;r<=(car.rows||20);r++)for(const col of car.cols||[]){if(m.has(`${r}${col}`))continue;total++;const id=typeof seatId==='function'?seatId(car,r,col):`${car.car}호차 ${r}${col}`;if(used.has(id))n++}return{total,remaining:Math.max(0,total-n)}}
function invalidateCongestion(no,date){for(const k of Object.keys(_bookedCache))if((!no||k.startsWith(no+':'))&&(!date||k.includes(':'+date+':')))delete _bookedCache[k];NIMBI_Inventory?.invalidate(no,date)}
