/* 기존 철도 데이터를 조합하는 운행 센터. 원본 시간표·상태는 변경하지 않는다. */
(function(g){'use strict';
const TABS=[['dashboard','운행 상황판'],['propagation','지연 전파 지도'],['history','운행 이력'],['platform','승강장 상황판'],['trip','여행 보드'],['favorite','즐겨찾기 센터'],['alert','알림 센터'],['revision','운행 변경 비교'],['pattern','서비스 패턴 비교']];
let active='dashboard',selectedTrain='',selectedStation='',selectedLine='';
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const M=v=>{const m=String(v||'').match(/(\d+):(\d+)/);return m?+m[1]*60+ +m[2]:null},C=v=>String(v||'').match(/\d{1,2}:\d{2}/)?.[0]||'—';
const all=()=>typeof ALL_TRAINS!=='undefined'&&Array.isArray(ALL_TRAINS)?ALL_TRAINS:[],stops=t=>(t?.stops||[]).filter(s=>g.hasTime?.(s.arr)||g.hasTime?.(s.dep));
const state=t=>{try{return g.getCurrentStatus(t)}catch(_){return null}},dly=t=>{try{return typeof _simDelayOn!=='undefined'&&_simDelayOn?g._liveDelayOf?.(t)||0:0}catch(_){return 0}},why=t=>{try{return g._simCauseSummary?.(t)||''}catch(_){return''}};
const phase=t=>{const s=state(t);return s?.status==='running'?'운행 중':s?.status==='before'?'운행 예정':'운행 종료'},place=t=>{const s=state(t);return s?.atStn||s?.passStn||s?.nextStn||stops(t)[0]?.s||'—'};
function cong(t){try{const s=stops(t);return g.getODCongestion?.(t,s[0]?.s,s.at(-1)?.s,g.todayLocalStr?.())}catch(_){return null}}
const trainLink=t=>`<button class="oc-link" onclick="openJourney('${E(t.no)}')">${E(t.grade)} ${E(t.no)}</button>`,empty=(a,b)=>`<div class="oc-empty"><strong>${E(a)}</strong><p>${E(b)}</p></div>`;
function head(){return `<header class="oc-head"><div><span>OPERATIONS CENTER</span><h1>운행 센터</h1><p>시간표·지연·승강장·여행 정보를 하나의 작업 공간에서 확인합니다.</p></div><time>${new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}</time></header><nav class="oc-tabs">${TABS.map(x=>`<button class="${x[0]===active?'active':''}" onclick="setOperationsHubTab('${x[0]}')">${x[1]}</button>`).join('')}</nav>`}
function picker(delayed=false){const a=all().filter(t=>!delayed||dly(t)>0).sort((x,y)=>String(x.no).localeCompare(String(y.no),0,{numeric:true}));if(!a.some(t=>String(t.no)===selectedTrain))selectedTrain=String(a[0]?.no||'');return `<label class="oc-field"><span>열차 선택</span><select onchange="selectOperationsTrain(this.value)">${a.map(t=>`<option value="${E(t.no)}" ${String(t.no)===selectedTrain?'selected':''}>${E(t.grade)} ${E(t.no)} · ${E(stops(t)[0]?.s)}→${E(t.dest)}</option>`).join('')}</select></label>`}
function dashboard(){const a=all(),run=a.filter(t=>phase(t)==='운행 중'),late=run.filter(t=>dly(t)>0),busy=run.filter(t=>(cong(t)?.percent||0)>=76),up=a.filter(t=>phase(t)==='운행 예정');return `<div class="oc-metrics">${[['운행 중',run.length],['운행 예정',up.length],['지연',late.length],['혼잡 이상',busy.length]].map(x=>`<article><span>${x[0]}</span><b>${x[1]}</b></article>`).join('')}</div><section class="oc-section"><header><h2>현재 철도망</h2><small>지연 우선</small></header>${run.length?`<div class="oc-table-wrap"><table><thead><tr><th>열차</th><th>노선</th><th>현재 위치</th><th>지연</th><th>혼잡</th><th></th></tr></thead><tbody>${run.sort((x,y)=>dly(y)-dly(x)).slice(0,20).map(t=>`<tr><td>${trainLink(t)}</td><td>${E(t.line)}</td><td>${E(place(t))}</td><td class="${dly(t)?'oc-warn':''}">${dly(t)?`+${dly(t)}분`:'정상'}</td><td>${E(cong(t)?.level||'—')}</td><td><button class="oc-mini" onclick="trackTrainOnMap('${E(t.no)}')">지도</button></td></tr>`).join('')}</tbody></table></div>`:empty('운행 중인 열차가 없습니다','현재 시각에 운행 중인 열차가 표시됩니다.')}</section>`}
function propagation(){const t=all().find(x=>String(x.no)===selectedTrain)||all().find(x=>dly(x)>0);if(!t)return picker(true)+empty('전파할 지연이 없습니다','지연 시뮬레이션을 켜면 관계가 표시됩니다.');selectedTrain=String(t.no);const s=stops(t),rep=g._simDelayReport?.(t),log=g._simEventLog?.(t,true)||[],dep=M(s[0]?.dep);const affected=all().filter(o=>o!==t&&stops(o).filter(q=>s.some(z=>z.s===q.s)).length>=2&&Math.abs((M(stops(o)[0]?.dep)??999)-(dep??0))<90).slice(0,8);return `${picker(true)}<section class="oc-section"><header><h2>${E(t.grade)} ${E(t.no)} 지연 전파</h2><b class="oc-warn">+${dly(t)}분</b></header><div class="oc-propagation"><article><b>최초 원인</b><strong>${E(rep?.first||why(t)||'운행 상황 반영')}</strong><span>${E(s[0]?.s)} → ${E(t.dest)}</span></article><i>→</i><div>${affected.map(o=>`<button onclick="selectOperationsTrain('${E(o.no)}')"><b>${E(o.no)}</b><span>${E(place(o))}</span><em>${dly(o)?`+${dly(o)}분`:'영향 감시'}</em></button>`).join('')||'<p>직접 영향을 받는 열차가 없습니다.</p>'}</div></div><h3>역별 변화</h3><ol class="oc-event-log">${log.slice(0,16).map(x=>`<li>${E(x)}</li>`).join('')||'<li>기록된 변화가 없습니다.</li>'}</ol><footer>종착 예상 ${rep?.final?`+${rep.final}분`:'정시'} · 회복 ${rep?.recovered||0}분</footer></section>`}
function history(){const t=all().find(x=>String(x.no)===selectedTrain)||all()[0];if(!t)return empty('열차가 없습니다','운행 이력을 표시할 수 없습니다.');selectedTrain=String(t.no);const s=stops(t),v=s.map((_,i)=>g._simDelayAtStop?.(t,i)||0),max=Math.max(0,...v),rec=v.reduce((n,x,i)=>n+(i&&v[i-1]>x?v[i-1]-x:0),0);try{const k='nimbi_operation_history',h=JSON.parse(localStorage.getItem(k)||'{}');h[`${g.todayLocalStr?.()}:${t.no}`]={date:g.todayLocalStr?.(),no:t.no,max,final:v.at(-1)||0,cause:why(t)};localStorage.setItem(k,JSON.stringify(h))}catch(_){}return `${picker()}<section class="oc-section"><header><h2>${E(t.grade)} ${E(t.no)} 운행 이력</h2><span>${E(s[0]?.s)} → ${E(t.dest)}</span></header><div class="oc-summary">${[['출발',v[0]?'지연':'정시'],['최대 지연',max+'분'],['회복',rec+'분'],['실제 종착',v.at(-1)?`+${v.at(-1)}분`:'정시']].map(x=>`<span>${x[0]}<b>${x[1]}</b></span>`).join('')}</div><div class="oc-history-line">${s.map((q,i)=>`<button onclick="openStationDetail('${E(q.s)}')"><i style="--d:${Math.min(100,v[i]*5)}%"></i><time>${C(q.arr||q.dep)}</time><strong>${E(q.s)}</strong><em>${v[i]?`+${v[i]}`:'0'}</em></button>`).join('')}</div><p class="oc-note">${E(why(t)||'특이 지연 원인이 기록되지 않았습니다.')}</p></section>`}
function platformNo(t,n){try{return g._platformForTrain?.(n+'역',n,g.getTrainsByStation?.(n)||[],t)??'—'}catch(_){return'—'}}
function platforms(){const names=[...new Set(all().flatMap(t=>stops(t).map(s=>s.s)))].sort((a,b)=>a.localeCompare(b,'ko'));if(!selectedStation)selectedStation=names[0]||'';const ts=(g.getTrainsByStation?.(selectedStation)||[]).filter(t=>!g.isPassStop?.(t,selectedStation)),groups={};ts.forEach(t=>(groups[platformNo(t,selectedStation)]??=[]).push(t));return `<label class="oc-field"><span>역 선택</span><input list="oc-stations" value="${E(selectedStation)}" onchange="selectOperationsStation(this.value)"><datalist id="oc-stations">${names.map(n=>`<option value="${E(n)}">`).join('')}</datalist></label><div class="oc-platform-grid">${Object.entries(groups).sort((a,b)=>String(a[0]).localeCompare(String(b[0]),0,{numeric:true})).map(([p,a])=>`<article class="oc-platform"><header><b>${E(p)}번 승강장</b><span>${a.length}편</span></header>${a.sort((x,y)=>(M(x.stops.find(s=>s.s===selectedStation)?.dep)||0)-(M(y.stops.find(s=>s.s===selectedStation)?.dep)||0)).slice(0,12).map(t=>{const q=t.stops.find(s=>s.s===selectedStation),here=place(t)===selectedStation;return `<button onclick="openJourney('${E(t.no)}')"><time>${C(q.dep||q.arr)}</time><strong>${E(t.grade)} ${E(t.no)}</strong><span>${E(t.dest)}</span><em class="${here?'live':''}">${here?'정차 중':phase(t)}</em></button>`}).join('')}</article>`).join('')||empty('운행 정보가 없습니다','다른 역을 선택해 주세요.')}</div>`}
function trips(){const a=g.loadTrips?.()||[];if(!a.length)return empty('등록된 여행이 없습니다','마이페이지에서 여행과 열차 일정을 추가해 주세요.');return a.map(t=>`<section class="oc-section"><header><h2>${E(t.name)}</h2><span>${E(t.startDate)} · ${t.days}일</span></header>${Array.from({length:t.days},(_,i)=>{const legs=(t.legs||[]).filter(l=>(l.day||1)===i+1).sort((x,y)=>(M(x.depTime)||0)-(M(y.depTime)||0));return `<div class="oc-trip-day"><b>${i+1}일차</b><div>${legs.map(l=>`<button onclick="openJourney('${E(l.trainNo)}')"><time>${E(l.depTime)}–${E(l.arrTime)}</time><strong>${E(l.trainNo)}</strong><span>${E(l.fromStn)} → ${E(l.toStn)}</span><em class="${l.ticketId?'done':''}">${l.ticketId?'예매 완료':'미예매'}</em></button>`).join('')||'<p>이동 일정 없음</p>'}</div></div>`}).join('')}<footer><button class="oc-link" onclick="openMyPage();openMySection('mytrip');openTrip('${E(t.id)}')">여행 상세·일괄 예매</button></footer></section>`).join('')}
function favorites(){const a=g.loadFavs?.()||[],groups=g.loadFavGroups?.()||[];if(!a.length)return empty('즐겨찾기가 없습니다','열차·역·경로를 추가하면 여기에 모입니다.');return `<div class="oc-fav-grid">${groups.map(gr=>`<section class="oc-section"><header><h2>${E(gr.label)}</h2><span>${a.filter(f=>(f.cat||'etc')===gr.id).length}</span></header>${a.filter(f=>(f.cat||'etc')===gr.id).map(f=>`<button class="oc-fav-row" onclick="openOperationsFavorite('${E(f.id)}')"><strong>${E(f.label)}</strong><span>${E(f.type)}</span></button>`).join('')||'<p class="oc-note">비어 있음</p>'}</section>`).join('')}</div>`}
function alerts(){const a=[...(g.loadAlarms?.()||[]).map(x=>['승하차',`${x.trainNo} · ${x.stn}`,x.time||'',!x.fired]),...(g.loadSeatWatches?.()||[]).map(x=>['좌석',`${x.trainNo} ${x.fromStn}→${x.toStn}`,x.seatClassLabel||'',x.active!==false])];return a.length?`<section class="oc-section"><header><h2>통합 알림</h2><button class="oc-link" onclick="openMyPage();openMySection('alarm')">설정</button></header><div class="oc-alert-list">${a.map(x=>`<article><b>${E(x[0])}</b><strong>${E(x[1])}</strong><span>${E(x[2])}</span><em>${x[3]?'활성':'완료'}</em></article>`).join('')}</div></section>`:empty('알림이 없습니다','승하차 또는 여석 알림을 설정해 주세요.')}
function revisions(){const notices=typeof NOTICES!=='undefined'?NOTICES:[],a=notices.filter(n=>/신설|개정|조정|증편|변경|연장|단축/.test(`${n.title} ${n.body}`)),current={};all().forEach(t=>{const s=stops(t);current[t.no]={grade:t.grade,line:t.line,from:s[0]?.s,to:s.at(-1)?.s,dep:C(s[0]?.dep),arr:C(s.at(-1)?.arr),stops:s.map(x=>x.s).join('|')}});let previous={};try{previous=JSON.parse(localStorage.getItem('nimbi_schedule_snapshot')||'{}')}catch(_){}const changes=[];if(Object.keys(previous).length){Object.keys(current).filter(n=>!previous[n]).forEach(n=>changes.push([n,'신설',`${current[n].from}→${current[n].to}`]));Object.keys(previous).filter(n=>!current[n]).forEach(n=>changes.push([n,'폐지',`${previous[n].from}→${previous[n].to}`]));Object.keys(current).filter(n=>previous[n]).forEach(n=>{const p=previous[n],q=current[n],fields=[];if(p.dep!==q.dep||p.arr!==q.arr)fields.push('시각');if(p.stops!==q.stops)fields.push('정차역');if(p.grade!==q.grade)fields.push('등급');if(p.line!==q.line||p.from!==q.from||p.to!==q.to)fields.push('구간');if(fields.length)changes.push([n,fields.join('·'),`${q.from}→${q.to}`])})}try{localStorage.setItem('nimbi_schedule_snapshot',JSON.stringify(current))}catch(_){}return `<section class="oc-section"><header><h2>직전 저장본과 자동 비교</h2><span>${changes.length}건</span></header>${changes.length?`<div class="oc-revision-list">${changes.map(x=>`<article><time>${E(x[0])}</time><strong>${E(x[2])}</strong><span>${E(x[1])}</span></article>`).join('')}</div>`:empty('변경 내역이 없습니다',Object.keys(previous).length?'현재 시간표가 직전 저장본과 같습니다.':'현재 시간표를 기준본으로 저장했습니다. 다음 개정부터 자동 비교됩니다.')}</section><section class="oc-section"><header><h2>공지 기반 변경 자료</h2><span>${a.length}건</span></header><div class="oc-revision-list">${a.slice().reverse().map(n=>`<article><time>${E(n.date)}</time><strong>${E(n.title)}</strong><span>${/신설|증편/.test(n.title)?'신설·증편':/단축|폐지/.test(n.title)?'단축·폐지':'운행 조정'}</span></article>`).join('')}</div><button class="oc-link" onclick="nimbiNavigate('notice')">공지 원문·첨부 시간표 보기</button></section>`}
function patterns(){const lines=[...new Set(all().map(t=>t.line))].sort((a,b)=>a.localeCompare(b,'ko'));if(!selectedLine)selectedLine=lines[0]||'';const groups={};all().filter(t=>t.line===selectedLine).forEach(t=>{const k=stops(t).map(s=>s.s).join('→');(groups[k]??=[]).push(t)});return `<label class="oc-field"><span>노선 선택</span><select onchange="selectOperationsLine(this.value)">${lines.map(l=>`<option ${l===selectedLine?'selected':''}>${E(l)}</option>`).join('')}</select></label><div class="oc-pattern-grid">${Object.values(groups).sort((a,b)=>b.length-a.length).slice(0,14).map(a=>{const t=a[0],s=stops(t),dur=(M(s.at(-1)?.arr||s.at(-1)?.dep)-M(s[0]?.dep||s[0]?.arr)+1440)%1440,cap=g.getTrainCapacity?.(t);return `<article class="oc-pattern"><header><b>${E(t.grade)}</b><span>${a.length}편</span></header><strong>${E(s[0]?.s)} → ${E(s.at(-1)?.s)}</strong><p>${s.length}개 정차역 · ${Math.floor(dur/60)}시간 ${dur%60}분 · 좌석 ${cap?.total||'—'}</p><div>${s.map(q=>`<span>${E(q.s)}</span>`).join('<i>›</i>')}</div><button onclick="openJourney('${E(t.no)}')">대표 열차 ${E(t.no)} 보기</button></article>`}).join('')||empty('운행 패턴이 없습니다','다른 노선을 선택해 주세요.')}</div>`}
function content(){return active==='dashboard'?dashboard():active==='propagation'?propagation():active==='history'?history():active==='platform'?platforms():active==='trip'?trips():active==='favorite'?favorites():active==='alert'?alerts():active==='revision'?revisions():patterns()}
g.renderOperationsHub=()=>{const el=document.getElementById('result-control');if(el)el.innerHTML=`<div class="oc-shell">${head()}<main>${content()}</main></div>`};g.setOperationsHubTab=id=>{if(TABS.some(x=>x[0]===id)){active=id;g.renderOperationsHub()}};g.selectOperationsTrain=n=>{selectedTrain=String(n);g.renderOperationsHub()};g.selectOperationsStation=n=>{selectedStation=n;g.renderOperationsHub()};g.selectOperationsLine=n=>{selectedLine=n;g.renderOperationsHub()};
g.openOperationsFavorite=id=>{const f=(g.loadFavs?.()||[]).find(x=>x.id===id);if(!f)return;if(f.type==='train')g.openJourney?.(f.data?.no||id.split(':')[1]);else if(f.type==='station')g.openStationDetail?.(f.data?.stn||id.split(':')[1]);else{g.nimbiNavigate?.('route');setTimeout(()=>{const a=document.getElementById('input-from'),b=document.getElementById('input-to');if(a)a.value=f.data?.from||'';if(b)b.value=f.data?.to||'';g.searchByRoute?.()},0)}};
})(window);
