(function(g){const C=(v,a,b)=>Math.max(a,Math.min(b,v)),H=s=>{let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0},R=s=>H(s)/4294967296,T=v=>{if(!/^\d{1,2}:\d{2}$/.test(v||''))return null;const[a,b]=v.split(':').map(Number);return a*60+b},S=t=>(t?.stops||[]).filter(x=>T(x.arr)!==null||T(x.dep)!==null);
function profile(n){if(g.NIMBI_STATION_DEMAND_PROFILE?.[n])return{...g.NIMBI_STATION_DEMAND_PROFILE[n]};const p=+g.STATION_PAX?.[n],w=p>0?C(.72+Math.sqrt(p/100)*.55,.72,1.27):1;return{origin:w,destination:w,business:1,leisure:1,transfer:p>=55?1.15:1,capital:false}}
function capacity(t){try{if(g.getCarComposition&&g.getFormationType){const x={standard:0,premium:0,standing:0};for(const c of g.getCarComposition(g.getFormationType(t.grade,t.no))){const n=+c.totalSeats||0;if(c.type==='special'||c.type==='premium')x.premium+=n;else if(c.type==='free')x.standing+=n||30;else x.standard+=n}return{total:x.standard+x.premium,...x}}}catch(e){}const q=/KTX$/.test(t?.grade)?999:/산천|SRT/.test(t?.grade)?453:/이음/.test(t?.grade)?416:/청춘/.test(t?.grade)?520:/새마을/.test(t?.grade)?312:/마음/.test(t?.grade)?208:360;return{total:q,standard:q,premium:0,standing:0}}
function game(t){const x=[t?.passengers,t?.pax,t?.passengerCount,t?.pax_boarded].map(Number).find(Number.isFinite);if(x>0)return x;const y=+g.NIMBI_GAME_PAX_PER_RUN?.[String(+t?.no)];return y>0?y:null}
function base(t){const p=game(t);return p>0?C(.55+Math.log1p(p/Math.max(1,capacity(t).total))*.38,.45,1.55):1}
const group=x=>/KTX|SRT/.test(x)?'high':/ITX/.test(x)?'itx':'local';
function km(t,a,b){try{const x=+g.routeDistanceKm?.(t,a.s,b.s);if(x>0)return x}catch(e){}const x=T(a.dep||a.arr),y=T(b.arr||b.dep);return x!=null&&y!=null?Math.max(8,(y<x?y+1440:y)-x)*1.25:30}
function dist(t,k){const q=group(t.grade);return k<50?q==='high'?.75:q==='itx'?1.12:1.1:k<150?q==='high'?1.03:q==='itx'?1.1:1:k<250?q==='high'?1.18:q==='itx'?1.02:.88:q==='high'?1.34:q==='itx'?.85:.7}
function direction(t,a,b,date){const d=new Date(date+'T12:00:00'),h=Math.floor((T(a.dep||a.arr)||720)/60),A=profile(a.s),B=profile(b.s);let m=1;if(d.getDay()>0&&d.getDay()<6&&h>=7&&h<10)m*=B.capital&&!A.capital?1.34:A.capital&&!B.capital?.92:1.08;if(d.getDay()>0&&d.getDay()<6&&h>=17&&h<21)m*=A.capital&&!B.capital?1.36:B.capital&&!A.capital?.96:1.1;if(d.getDay()===5&&h>=16&&A.capital&&!B.capital)m*=1.14;if(d.getDay()===0&&h>=14&&B.capital&&!A.capital)m*=1.22;if(d.getDay()===6&&h<12&&(B.leisure||1)>1.25)m*=1.2;return C(m,.78,1.48)}
function cal(date,b){const d=new Date(date+'T12:00:00'),holiday=typeof g._simIsKoreanHoliday==='function'&&g._simIsKoreanHoliday(d);let m=NIMBI_DAY_MULTIPLIERS[d.getDay()]||1,mo=d.getMonth()+1;if(holiday)m=Math.max(m,1.1);if((mo===7||mo===8)&&(profile(b.s).leisure||1)>1.2)m*=1.12;if((mo===10||mo===11)&&(profile(b.s).leisure||1)>1.2)m*=1.08;return C(m,.7,1.65)}
function score(t,a,b,date){const k=km(t,a,b);return profile(a.s).origin*profile(b.s).destination*C(.8+Math.log1p(k)/9,.85,1.35)*dist(t,k)*direction(t,a,b,date)*cal(date,b)*base(t)*(.91+R(`${t.no}|${date}|${a.s}|${b.s}`)*.18)}
const cache=new Map;function build(t,date){const key=t.no+'|'+date+'|'+NIMBI_DEMAND_VERSION;if(cache.has(key))return cache.get(key).map(x=>({...x}));const ss=S(t),o=[];for(let i=0;i<ss.length-1;i++)for(let j=i+1;j<ss.length;j++)o.push({from:ss[i].s,to:ss[j].s,fromIndex:i,toIndex:j,score:score(t,ss[i],ss[j],date)});if(!o.length)return[];const cap=capacity(t).total,target=Math.round(C((game(t)||cap*.82)*C(.75+Math.sqrt(ss.length)/5,.9,1.8),cap*.25,cap*2)),sum=o.reduce((a,x)=>a+x.score,0)||1;let n=0;for(const x of o){const z=target*x.score/sum;x.demand=Math.floor(z);x.frac=z-x.demand;n+=x.demand}o.sort((a,b)=>b.frac-a.frac);for(let i=0;i<target-n;i++)o[i%o.length].demand++;o.sort((a,b)=>a.fromIndex-b.fromIndex||a.toIndex-b.toIndex);cache.set(key,o);return o.map(x=>({...x}))}
g.NIMBI_Demand={clamp:C,hash:H,random:R,toMin:T,getStops:S,getStationDemandProfile:profile,getTrainCapacity:capacity,getGamePassengerCount:game,getBaseDemandIndex:base,getDistanceGradePreference:dist,getTimeDirectionMultiplier:direction,getODDemandScore:score,buildTrainODDemand:build};g.getBaseDemandIndex=base;g.buildTrainODDemand=build;g.getStationDemandProfile=profile})(window);
